name: Publish SNAPSHOT Package
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: build -x check

    - name: Publish to Repsy
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: publishAllPublicationsToMavenRepository -x check
      env:
        USERNAME: ${{ secrets.REPSY_USERNAME }}
        PASSWORD: ${{ secrets.REPSY_PASSWORD }}
